In [43]:
class Area(): # Clase para calcular el área y perímetro de un triángulo
    def __init__(self, lado_a, lado_b, lado_c, altura): # Inicializa los atributos de la clase
        self.lado_a = lado_a
        self.lado_b = lado_b
        self.lado_c = lado_c
        self.altura = altura
    def tipo_triangulo(self): # Determina el tipo de triángulo según sus lados usando if y else
        if self.lado_a == self.lado_b and self.lado_b == self.lado_c:
            return 'Equilátero'

        elif self.lado_a == self.lado_b or self.lado_a == self.lado_c or self.lado_b == self.lado_c:
            return 'Isósceles'

        else:
            return 'Escaleno'
    def perimetro(self): # Calcula el perímetro del triángulo
        perimetro = (self.lado_a + self.lado_b + self.lado_c)
        return perimetro

    def area_triangulo(self): # Calcula el área del triángulo
        area = ((self.lado_b * self.altura)/2)
        return area

    def mostrar_area(self): # Muestra el área del triángulo
        tipo = self.tipo_triangulo()
        area = self.area_triangulo()
        print(f"El área del triángulo {tipo} es {area}")


    def mostrar_perimetro(self):  # Muestra el perímetro del triángulo
        tipo = self.tipo_triangulo()
        perimetro = self.perimetro()
        print(f"El perímetro del triángulo {tipo} es {perimetro}")




In [59]:
class Felicitaciones(Area): # Clase para mostrar un mensaje de felicitación
  def __init__(self):
    print('felicidades')
  def mensaje(self):
    print('resolviste correctamente el área y perímetro')

In [62]:
area = Area(5,5,5,10) # Cree un objeto de la clase Area con lado_a = 5, lado_b = 5, lado_c = 5 y altura = 10
area.tipo_triangulo()
area.perimetro()
area.mostrar_area()
area.mostrar_perimetro()
felicitaciones = Felicitaciones()
felicitaciones.mensaje()



El área del triángulo Equilátero es 25.0
El perímetro del triángulo Equilátero es 15
felicidades
resolviste correctamente el área y perímetro


In [63]:
area = Area(5,3,5,10)
area.tipo_triangulo()
area.perimetro()
area.mostrar_area()
area.mostrar_perimetro()
felicitaciones = Felicitaciones()
felicitaciones.mensaje()

El área del triángulo Isósceles es 15.0
El perímetro del triángulo Isósceles es 13
felicidades
resolviste correctamente el área y perímetro


In [64]:
area = Area(5,8,2,9)
area.tipo_triangulo()
area.perimetro()
area.mostrar_area()
area.mostrar_perimetro()
felicitaciones = Felicitaciones()
felicitaciones.mensaje()

El área del triángulo Escaleno es 36.0
El perímetro del triángulo Escaleno es 15
felicidades
resolviste correctamente el área y perímetro


In [3]:
import numpy as np
lista = np.random.randint(1,101,16)
lista


array([66, 94, 90, 98, 31, 14, 55, 16,  3, 98, 36, 18,  5, 35, 35, 57])

In [4]:
matriz = np.reshape(lista, (4, 4))
matriz

array([[66, 94, 90, 98],
       [31, 14, 55, 16],
       [ 3, 98, 36, 18],
       [ 5, 35, 35, 57]])

In [5]:
determinante = np.linalg.det(matriz)
transpuesta = matriz.T

In [6]:
determinante


-9446399.999999993

In [7]:
transpuesta

array([[66, 31,  3,  5],
       [94, 14, 98, 35],
       [90, 55, 36, 35],
       [98, 16, 18, 57]])