#Matrices

In [4]:
import numpy as np

In [7]:
np.random.randint(1,21, size=15)

array([20, 20, 20, 15,  4,  1,  5, 11,  9,  5,  9, 13, 18, 20,  1])

In [11]:
L=[i for i in np.random.randint(1,21, size=15) if i%2==0]
L.sort() #ordenar ascendentemente
L

[16, 10, 14, 6, 16, 4, 4, 2, 14, 2, 20, 8]

In [22]:
L.pop()#muestra el más grande

6

In [21]:
L.remove(4) #quita un número - solo puedes poner uno por uno

In [23]:
L+[4]

[16, 10, 14, 16, 4, 14, 20, 4]

In [24]:
L.pop(3)

16

In [25]:
L_arreglo = np.array(L)
L_arreglo

array([16, 10, 14,  4, 14, 20])

In [26]:
len(L_arreglo)

6

In [33]:
L_arreglo.reshape(2,3)

array([[16, 10, 14],
       [ 4, 14, 20]])

In [55]:
L_matriz = L_arreglo.reshape(2,3)
L_matriz

array([[16, 10, 14],
       [ 4, 14, 20]])

In [36]:
L_arreglo.reshape(1,6)

array([[16, 10, 14,  4, 14, 20]])

In [46]:
M_matriz = np.array([2, 3, 14, 19, 13, 9]).reshape(3,2)
M_matriz

array([[ 2,  3],
       [14, 19],
       [13,  9]])

In [56]:
N = L_matriz @ M_matriz
N

array([[354, 364],
       [464, 458]])